export const types = {
  SEND_REQUEST_GET_ALL_USER: 'SEND_REQUEST_GET_ALL_USER',
  SEND_REQUEST_GET_ALL_USER_SUCCESS: 'SEND_REQUEST_GET_ALL_USER_SUCCESS',
  SEND_REQUEST_GET_ALL_USER_FAILURE: 'SEND_REQUEST_GET_ALL_USER_FAILURE',
  SEND_REQUEST_GET_ALL_PHOTOS: 'SEND_REQUEST_GET_ALL_PHOTOS',
  SEND_REQUEST_GET_ALL_PHOTOS_SUCCESS: 'SEND_REQUEST_GET_ALL_PHOTOS_SUCCESS',
  SEND_REQUEST_GET_ALL_PHOTOS_FAILURE: 'SEND_REQUEST_GET_ALL_PHOTOS_FAILURE',
  SEND_REQUEST_GET_DETAILS_USER: 'SEND_REQUEST_GET_DETAILS_USER',
  SEND_REQUEST_GET_DETAILS_USER_SUCCESS:
    'SEND_REQUEST_GET_DETAILS_USER_SUCCESS',
  SEND_REQUEST_GET_DETAILS_USER_FAILURE:
    'SEND_REQUEST_GET_DETAILS_USER_FAILURE',
  SEND_REQUEST_GET_DETAILS_PHOTOS: 'SEND_REQUEST_GET_DETAILS_PHOTOS',
  SEND_REQUEST_GET_DETAILS_PHOTOS_SUCCESS:
    'SEND_REQUEST_GET_DETAILS_PHOTOS_SUCCESS',
  SEND_REQUEST_GET_DETAILS_PHOTOS_FAILURE:
    'SEND_REQUEST_GET_DETAILS_PHOTOS_FAILURE',

  SEND_REQUEST_DELETE_USER: 'SEND_REQUEST_DELETE_USER',
  SEND_REQUEST_DELETE_USER_SUCCESS: 'SEND_REQUEST_DELETE_USER_SUCCESS',
  SEND_REQUEST_DELETE_USER_FAILURE: 'SEND_REQUEST_DELETE_USER_FAILURE',
  DELETE_DATA_FROM_STORE: 'DELETE_DATA_FROM_STORE',
  DELETE_PHOTO_FROM_STORE: 'DELETE_PHOTO_FROM_STORE',
};
